# Site settings
title: Good Clean Read
tag_text: Good Clean Read
description: A responsive template for publishing single-page websites, articles that are easy on the eyes
url: "https://aclloyd97.github.io"
baseurl: "/backyard-weatherman"

font-awesome-include: true # make this false if you don't need font-awesome

# About/contact
author:
  name:              Andrea Lloyd
  url:               https://aclloyd9.wixsite.com/portfolio
  email:             aclloyd@tamu.edu

# Custom vars
version:             1.0.0
date:                12/11/2018

# Build settings
markdown: kramdown

exclude: ["README.md"]
