# Site settings
title: Backyard Weatherman
tag_text: Backyard Weatherman
description: An English Indepedent Study Project on Science and Data Communication
url: "https://aclloyd97.github.io"
baseurl: "/backyard-weatherman"

font-awesome-include: true # make this false if you don't need font-awesome

# About/contact
author:
  name:              Andrea Lloyd
  url:               https://aclloyd9.wixsite.com/portfolio
  email:             aclloyd@tamu.edu

# Custom vars
version:             1.0.0
date:                12/11/2018

# Build settings
markdown: kramdown

exclude: ["README.md"]
